// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edgmccvuxjhnvhmfnhcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkZ21jY3Z1eGpobnZobWZuaGNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0Njg4MTUsImV4cCI6MjA1MTA0NDgxNX0.y_UGrxfPjbCQBisXX8rsBKiQWlbwZESgw14XuF7YgcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);